//
// Machine.cpp for hh in /home/nuts/local/hell/hell/purgatory/etape1
// 
// Made by Rivot Corentin (nuts)
// Login   <corentin.rivot@gmail.com>
// 
// Started on  Sat Dec 15 00:51:05 2012 Rivot Corentin
// Last update Sat Dec 15 11:00:43 2012 Rivot Corentin
//

#include "Machine.hpp"


eState gStateTable[STATE_MAX][EDGE_MAX] {
  { S1, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR},
  { STATE_ERROR, S2, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR},
  { STATE_ERROR, STATE_ERROR, S3, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR},
  { STATE_ERROR, STATE_ERROR, STATE_ERROR, S4, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR},
  { STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, S5, STATE_ERROR, STATE_ERROR, STATE_ERROR},
  { STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, S6, STATE_ERROR, STATE_ERROR},
  { STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR,  S7, STATE_ERROR},
  { STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR},

};


eAction gActionTable[STATE_MAX][EDGE_MAX] {
  { MA, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR},
    { ACTION_ERROR, MA, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR},
  { ACTION_ERROR, ACTION_ERROR, MA, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR},
  { ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, MA, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR},
  { ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, MA, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR},
    { ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, MA, ACTION_ERROR, ACTION_ERROR},
    { ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR,  MA, ACTION_ERROR},
    { HR, HR, HR, HR, HR, HR, HR, HR},

};



